Add support for Github Tokens to read data.
mikeconley/myqonly pull request #48
Opened 2021-02-17 19:54 UTC by Callek

Fixes #46

2021-02-17 19:55 UTC, Callek commented
Formatting changes courtesy of VS Code, but I can edit them out if desired.

2021-05-07 18:01 UTC, mikeconley requested changes
Hey @Callek,

Thanks for the patch!

There are a number of unrelated changes in this patch - a lot of them seem to be whitespace changes that `yarn lint` doesn't seem to like.

Could you please:

1. Run `yarn lint --fix` to revert any of the changes the ESLint isn't happy with
2. Revert any unrelated whitespace changes

I _think_ this looks pretty reasonable though! Thanks for this.

2021-05-21 18:24 UTC, mikeconley approved these changes

2021-05-21 18:24 UTC, merged

2021-05-21 18:24 UTC, mikeconley commented
Thanks!